spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jichini_db?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: thdk5238!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
    show-sql: true
    open-in-view: false
